// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyayuagxtfnpfbtegufj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5YXl1YWd4dGZucGZidGVndWZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2NTAyMjQsImV4cCI6MjA1MDIyNjIyNH0.yjozCDQz5hq9OenMZMD6q28fKks_lyYlZetZtMAo10o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);